### ISSUE TITLE
Example script is failing due to Bioformats error

### ISSUE THREAD

**Issue by kmdouglass** [jries/fit3Dcspline#2]
The *example_3d_fit.m* script is failing at line 47, `calibrate_GUI` when the Calculate bead calibration button callback is run. After I enabled error printing as described in #1 , I discovered that the error is due to Bioformats.

Here's the minimum script required to produce the error. It should be run from the fit3Dcspline root directory:

```
addpath('bfmatlab')
addpath('shared')
filename = fullfile('data', 'beadstacks_3D_astig', 'stack3D_1.tif');
img = bfopen(filename);
```

Here's my info:
fit3Dcspline commit: 54028d3
MATLAB version: R2017A, 64 bits
Windows Server 2012 R2
Java heap space: 2048 MB

I'm guessing for now I can workaround this by not using Bioformats.

Error message:
```
>> addpath('bfmatlab')
addpath('shared')
filename = fullfile('data', 'beadstacks_3D_astig', 'stack3D_1.tif');
img = bfopen(filename);

09:23:00.108 [main] DEBUG loci.common.NIOByteBufferProvider - Using mapped byte buffer? false

Error using bfGetReader (line 85)
Java exception occurred:
loci.formats.UnknownFormatException: Unknown file format: C:\Users\laboleb\src\fit3Dcspline\data\beadstacks_3D_astig\stack3D_1.tif

	at loci.formats.ImageReader.getReader(ImageReader.java:190)

	at loci.formats.ImageReader.setId(ImageReader.java:832)

	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)

	at loci.formats.ChannelFiller.setId(ChannelFiller.java:223)

	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)

	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:291)


Error in bfopen (line 114)
r = bfGetReader(id, stitchFiles);
 
```

**Comment by jries** [comment]
Somehow bioformats was suddenly very slow opening micromanager files. I downloaded the new version, this must have killed it. I am working on my own tiff reader (should take a few days). But if anyone knows how to use bioformats, let me know.

**Comment by jries** [comment]
I now replaced the bio formats reader with my own reader based on the Matlab Tiff class. Let me know if there are still issues
